views/logout.py
from flask import Blueprint
from flask import Flask
from flask import render_template
from flask import session
from flask import request
from flask import redirect
from flask import url_for
import MySQLdb



logout = Blueprint("logout", __name__)
@logout.route("/logout")
def main():
	session.pop("email",None)
	session.pop("user_id",None)
	session.pop("language",None)
	session.pop("category",None)
	session.pop("sub_category",None)
	return redirect(url_for("home.main"))

views/show_history.py
from flask import Blueprint
from flask import Flask
from flask import render_template
from flask import session
from flask import request
from flask import redirect
from flask import url_for
from utils import application_constant
import MySQLdb

show_history = Blueprint("show_history", __name__)
@show_history.route("/show_history")
def main():
	if(session.get("user_id",False)):
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor()
		cursor.execute("select video_key,date_and_time, title from history where user_id = %d order by date_and_time"%session["user_id"])
		result = cursor.fetchall()
		cursor.execute("select name from user where id = %d"%session["user_id"])
		result2 = cursor.fetchall()
		cursor.execute("select profile_pic from user where id = %d"%session["user_id"])
		result3 = cursor.fetchall()
		video_keys = []
		user_info = result2[0][0]
		profile_pic = result3[0][0]
		for row in result:
			video_keys.append(row)
		video_keys.reverse()
		return render_template("history.html", video_keys = video_keys,user_info = user_info,profile_pic = profile_pic, user_email = session["email"])
	else:
	    return redirect(url_for("home.main"))

views/signup.py
from flask import Blueprint
from flask import Flask
from flask import render_template
from flask import session
from flask import request
from werkzeug.security import generate_password_hash
from flask import redirect
from flask import url_for
from utils import application_constant
import datetime
import MySQLdb

signup = Blueprint("signup", __name__)
@signup.route("/signup", methods= ["GET", "POST"])
def main():
	if(request.method == "GET"):
		if(session["email"]):
			return redirect(url_for("home.main"))
		else:
			return render_template("signup.html")
	else:
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor()
		name = request.form["name"]
		email = request.form["email"]
		password = request.form["password"]
		password = generate_password_hash(password)
		cursor.execute("""select email from user where email = "%s" """%(email))
		result=cursor.fetchall()
		if(not result):
			date_time = datetime.datetime.now()
			f = "%Y-%m-%d %H:%M:%S"
			date_time = date_time.strftime(f)
			cursor.execute("""insert into user(name,email,password, date_joined) values ("%s","%s","%s","%s") """%(name,email,password, date_time))
			cursor.execute("commit")
			cursor.close()
			db.close()
			return redirect(url_for("login.main"))
		else:
			cursor.close()
			db.close()
			return render_template("signup.html", error="This account already exists")

views/verification_link_generation.py
from flask import Blueprint
from flask import Flask
from flask import render_template
from flask import session
from flask import request
from werkzeug.security import generate_password_hash
from flask import redirect
from flask import url_for
from send_email import send_email
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from utils import application_constant
import datetime
import MySQLdb

verification_link_generation = Blueprint("verification_link_generation", __name__)
@verification_link_generation.route("/signup", methods= ["GET", "POST"])
def main():
	if(request.method == "GET"):
		if(session["email"]):
			return redirect(url_for("home.main"))
		else:
			return render_template("signup.html")
	else:
		db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
		cursor = db.cursor()
		name = request.form["name"]
		email = request.form["email"]
		password = request.form["password"]
		password = generate_password_hash(password)
		cursor.execute("""select email from user_temporary where email = "%s" """%(email))
		result=cursor.fetchall()
		if(not result):
			date_time = datetime.datetime.now()
			f = "%Y-%m-%d %H:%M:%S"
			date_time = date_time.strftime(f)
			confirmed = "false"
			cursor.execute("""insert into user_temporary(name,email,password, date_joined, confirm) values ("%s","%s","%s","%s","%s") """%(name,email,password, date_time, confirmed))
			cursor.execute("commit")
			cursor.execute("""select id from user_temporary where email = "%s" """%(email))
			id = cursor.fetchall()[0][0]
			s = Serializer("abc", salt = "activate-salt", expires_in = 3600)
			token = s.dumps({ 'id': id })
			cursor.close()
			db.close()
			msg = MIMEMultipart('alternative')
			t = render_template("verification_link_generation.html", name = name, token = token)
			to_be_sent = MIMEText(t,"html")
			msg.attach(to_be_sent)
			send_email(msg.as_string(),email)
			return "please check your email"
		else:
			cursor.execute("""select id,confirm from user_temporary where email = "%s"  """%(email))
			result = cursor.fetchall()[0]
			id = result[0]
			confirmed = result[1]
			if(confirmed == "false"):
				s = Serializer("abc", salt = "activate-salt", expires_in = 50)
				token = s.dumps({ 'id': id })
				return token+"this is seconed time"
			else:
				return "this account already exists"

views/verify_account.py
from flask import Blueprint
from flask import render_template
import itsdangerous
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import redirect
from flask import url_for
from utils import application_constant
import MySQLdb

verify_account = Blueprint("verify_account", __name__)

@verify_account.route("/verify_account/<token>")
def main(token):

	db = MySQLdb.connect(application_constant.SERVER, application_constant.USER, application_constant.PASSWORD, application_constant.DATABASE)
	cursor = db.cursor()
	s = Serializer("abc", salt = "activate-salt")
	try:
		data = s.loads(token)
		id = data["id"]
		cursor.execute(" select confirm from user_temporary where id = %d "%id)
		confirmed = cursor.fetchall()[0][0]
		if(confirmed == "false"):
			cursor.execute(""" update user_temporary set confirm="true" where id = %d"""%id)
			cursor.execute(""" select name, password, email, date_joined from user_temporary where id = %d"""%id)
			result = cursor.fetchall()[0]
			name = result[0]
			password = result[1]
			email = result[2]
			date_joined = result[3]
			cursor.execute(""" insert into user (name, password, email, date_joined) values("%s", "%s", "%s", "%s") """%(name, password, email, date_joined))
			cursor.execute("commit")
			message ="your account has been verified"
			return render_template("verify_account.html", message = message)
		else:
			return redirect(url_for("login.main"))
	except itsdangerous.SignatureExpired:
	    message = "Your verification period has expired please issue a new verification link"
	    return render_template("verify_account.html", message = message)
	cursor.close()
	db.close()

templates/history.html
<!DOCTYPE html>
<head>
	<title>You player</title>
	<meta charset="UTF-8">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="{{url_for("static", filename="jquery.lazy.min.js") }}"></script>
  <script src="{{url_for("static", filename="jQuery.tubeplayer.min.js") }}"></script>
<style type="text/css">
#myModal
{
  padding-top: 100px;
}
.title
{
    padding-left:30px;
}
body
{
  background-color: #ccccff;
}
img.lazy
{
  display: block;
}
hr
{
  background-color: black;
  width: 65%;
}
fieldset
{
	border:2px solid black;
    border-radius:5px;
	width:60%;
}
#center-panel
{
  padding-top: 30px;
}
</style>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{{url_for("home.main") }}">Home</a></li>
      <li class="active"><a href="{{ url_for("show_history.main") }}">History</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if user_email %}
    <li><a href="{{ url_for("logout.main") }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% endif %}
    </ul>
  </div>
</nav>
<div class="modal" id="myModal" role="dialog">
  <center><div id="player">
  </div></center>
</div>
<div class="row">
<div class="col-sm-2" id = "left-panel">
</div>
<div class="col-sm-8">
  <div id="center-panel">
  {% for key in video_keys %}
    <hr>
	<fieldset  style=" !important" >
	<table width="75%">
	<tr>
	<td rowspan='2'>
    <img class ="lazy" class="img-thumbnail" data-src="http://img.youtube.com/vi/{{ key[0] }}/0.jpg" height="150px" width="200px" onClick = 'return play_video("{{ key[0] }}");'>
	</td>
	<td class="title">{{ key[2] }}</td>
	</tr>
	<tr>
	<td class="title">
	    {{ key[1] }}
    </td>
	</tr>
	</table>
	</fieldset>
    <hr>
{% endfor %}
</div>
</div>
<div class="col-sm-2" id = "right-panel">
</div>
</div>
<script type="text/javascript">
$(function() {
        $('.lazy').lazy({
            placeholder: "data:image/gif;base64,R0lGODlhEALAPQAPzl5uLr9Nrl8e7..."
        });
    });
configuration = {
    width: 800, // the width of the player
    height: 500, // the height of the player
    allowFullScreen: "true", // true by default, allow user to go full screen
    preferredQuality: "default",// preferred quality: default, small, medium, large, hd720
    onPlayerEnded: function(){
        alert($(this).tubeplayer("videoId"));
        },
     onPlayerPlaying: function()
     {
        if(last_video_saved != $(this).tubeplayer("videoId"))
          {
            $.post("{{ url_for("save_to_history.main") }}", {video_key: $(this).tubeplayer("videoId")});
            last_video_saved = $(this).tubeplayer("videoId");
            alert($(this).tubeplayer("videoId"));
          }
     },
     //showControls: false,
     theme:"light",
     color:"white",
};

function play_video(key)
{
  var html = '<div id='+'"'+key+'"'+'>'+'</div>';
  var id = '#'+key+'';
  document.getElementById("player").innerHTML = html;
  configuration["initialVideo"]=key;
  $("#myModal").modal();
  $(id).tubeplayer(configuration);
}
</script>
</body>

templates/home3.html
<!DOCTYPE html>
<head>
	<title>You player</title>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></scrip>
<script src="{{ url_for("static", filename="jquery-1.12.1.min.js") }}"></script>
<script src="{{url_for("static", filename="jQuery.tubeplayer.min.js") }}"></script>
<style type="text/css">
#category-select
{
  padding-top: 50%;
}
.modal-header, h4, .close {
      background-color: black;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
 .modal-footer {
      background-color: black;
  }

 body
{
    background-color: #ccccff;
}
/*
  background-color: #b3b3b3;

*/
#sub-category-select
{
  padding-top: 10px;
}
#language-select
{
  padding-top: 10px;
}
.btn-group-vertical
{
  width: 100%;
}
#player
{
    text-align: center;
    padding-top: 10px;
}
</style>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


    <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form action = "{{url_for("login.main") }}" method="POST" role="form">
            <div class="form-group">
              <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="email" name = "email" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="password" name ="password" class="form-control" id="psw" placeholder="Enter password">
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        </div>
      </div>

    </div>
  </div>





<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      {% if user_email %}
      <li><a href="{{url_for("show_history.main") }}">History</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user_email %}

    <li id="login"><a href="#" onclick = "return false;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <li><a href="{{url_for("verification_link_generation.main") }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    {% else %}
    <li><a href="{{ url_for("logout.main") }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% endif %}
    </ul>
</div>

</nav>
<div class="row">
<div class="col-sm-2" id = "left-panel">
  <select class="form-control" id="language-select">
        {% for language in language_options %}
        <option value="{{language}}" id="language-select-option">{{language }}</option>
        {% endfor %}
  </select>
  <div id="category-select">
  </div>

</div>
<div class="col-sm-8">
  <div id="player">
  </div>
  <div id = "control">
    <center><button id="change" type = "button" class = "btn btn-primary">CHANGE</button></center>
  </div>
</div>
<div class="col-sm-2" id = "right-panel">
  <div id="sub-category-select">
  </div>
</div>
</div>
<script>
category_html="";
sub_category_html="";
last_video_saved="";
configuration = {
    width: 800, // the width of the player
    height: 500, // the height of the player
    allowFullScreen: "true", // true by default, allow user to go full screen
    initialVideo: "dHjmFnuxSok",
    preferredQuality: "default",// preferred quality: default, small, medium, large, hd720
    onPlayerEnded: function(){
        alert($(this).tubeplayer("videoId"));
        },
     onPlayerPlaying: function()
     {
        if(last_video_saved != $(this).tubeplayer("videoId"))
          {
            $.post("{{ url_for("save_to_history.main") }}", {video_key: $(this).tubeplayer("videoId")});
            last_video_saved = $(this).tubeplayer("videoId");
            alert($(this).tubeplayer("videoId"));
          }
     },
     //showControls: false,
     theme:"light",
     color:"white",
};
configuration["initialVideo"] = "{{ key }}"
jQuery("#player").tubeplayer(configuration);
$("#change").click(function(){
 $.get("{{ url_for("play_video.main") }}", function(key){
    html ='<div id ="'+key+'"'+'>'+'</div>';
    document.getElementById("player").innerHTML = html;
    configuration["initialVideo"] = key;
    id ="#"+key;
    $(id).tubeplayer(configuration);
  });
});
function set_sub_category(sub_category,id)
{
  $.post("{{url_for("change_sub_category.main") }}",{selected_sub_category:sub_category});
  document.getElementById("sub-category-select").innerHTML = sub_category_html;
 id="#"+id;
 $(id).css("color","black");
  return true;
}
function set_category(category,id)
{
  $.post("{{url_for("change_category.main") }}",{selected_category:category},function(data){
    html = '<div class="btn-group-vertical">';
    for(i=0;i<data["sub_category"].length;i++)
    {
       num = (i+1).toString()+"c";
       html = html + "<button href="+"'"+"#"+"'"+' '+'id='+'"'+num+'"'+ "class='btn btn-primary' type = 'button' onClick='return set_sub_category("+'"'+data["sub_category"][i]+'"'+","+'"'+num+'"'+");"+ "'"+">"+data["sub_category"][i]+"</button>";
    }
     html = html+"</div>";
     sub_category_html=html;
    document.getElementById("sub-category-select").innerHTML = html;
  });
  document.getElementById("category-select").innerHTML = category_html;
  id="#"+id;
 $(id).css("color","black");
  return false;
}
$(document).ready(function(){
$("#login").click(function(){
     $("#myModal").modal();
});
$("#language-select").click(function(){
  var selected_language=document.getElementById('language-select').value;
  $.post("{{ url_for("change_language.main")}}",{selected_language:selected_language},function(data){
    html= '<div class="btn-group-vertical">';
    for(var i=0;i<data["category"].length;i++)
    {
      num = (i+1).toString();
      html = html + "<button href="+"'"+"#"+"'"+' '+'id='+'"'+num+'"'+ "class='btn btn-primary' type = 'button' onClick='return set_category("+'"'+data["category"][i]+'"'+","+'"'+num+'"'+");"+ "'"+">"+data["category"][i]+"</button>";
    }
    html=html+"</div>";
    category_html=html;
    document.getElementById("sub-category-select").innerHTML = "";
    document.getElementById("category-select").innerHTML = html;
  });
});
});
</script>

</body>

templates/index.html
<!DOCTYPE html>
<head>
	<title>FaceTube</title>
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
	<meta charset="UTF-8">
	<style>
	 body
    {
        background-color: #ccccff;
    }
	#form-style
	{
		text-align: center;
		margin-top: 50px;
	}
    </style>
</head>
<body>

    <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user_email %}
    <li><a href="{{ url_for("login.main") }}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <li><a href="{{url_for("verification_link_generation.main") }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    {% endif %}
    </ul>
</div>

</nav>



    <form action = "" method = "POST">
        <div class="form-group">
            <label for="inputEmail">Email</label>
            <input type="email" class="form-control" id="inputEmail" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="inputPassword">Password</label>
            <input type="password" class="form-control" id="inputPassword" placeholder="Password">
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        </form>


	</div>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<head>
	<title>FaceTube</title>
	<meta charset="UTF-8">
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <style type="text/css">
    .modal-header, h4, .close {
      background-color: black;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
 .modal-footer {
      background-color: black;
  }

	body
	{
        background-color:#ccccff;
	}
	#form-style
	{
		text-align: center;
		margin-top: 50px;
	}

	</style>
</head>
<body>

    <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form action = "{{url_for("login.main") }}" method="POST" role="form">
            <div class="form-group">
              <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" name = "email" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="text" name ="password" class="form-control" id="psw" placeholder="Enter password">
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        </div>
      </div>

    </div>
  </div>





     <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user_email %}
    <li id="login"><a href="#" onclick = "return false;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <li><a href="{{url_for("verification_link_generation.main") }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    {% endif %}
    </ul>
</div>

</nav>

	<div id = "form-style">
		{% if error %}
		{{ error }}
		{% endif %}
	<form action="" method="POST">
		<input type="text" name="name" placeholder="Name"><br>
		<input type="email" name="email" placeholder="Email"><br>
		<input type="password" name="password" placeholder="Enter password"><br>
		<input type="text" name="password1" placeholder="Repeat password"><br>
		<input type="submit" value="SIGNUP">
	</form>



	</div>
<script>
    $(document).ready(function(){
        $("#login").click(function(){
     $("#myModal").modal();
});
    });
</script>
</body>
</html>

templates/verification_link_generation.html
<!DOCTYPE html>
<head>
	<meta charset="UTF-8">
</head>
<body>
	<h1>Hi, {{ name }}</h1>
	<p>Click on the below link to verify your account.</p>
	{{ url_for("verify_account.main", token = token, _external = True) }}
	
</body>

templates/verify_account.html
<!DOCTYPE html>
<head>
	<title>You player</title>
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></scrip>
<script src="{{ url_for("static", filename="jquery-1.12.1.min.js") }}"></script>
<style type="text/css">
.modal-header, h4, .close {
      background-color: black;
      color:white !important;
      text-align: center;
      font-size: 30px;
  }
 .modal-footer {
      background-color: black;
  }

 body
{
    background-color: #ccccff;
}
</style>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>


    <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header" style="padding:35px 50px;">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4><span class="glyphicon glyphicon-lock"></span> Login</h4>
        </div>
        <div class="modal-body" style="padding:40px 50px;">
          <form action = "{{url_for("login.main") }}" method="POST" role="form">
            <div class="form-group">
              <label for="usrname"><span class="glyphicon glyphicon-user"></span> Username</label>
              <input type="text" name = "email" class="form-control" id="usrname" placeholder="Enter email">
            </div>
            <div class="form-group">
              <label for="psw"><span class="glyphicon glyphicon-eye-open"></span> Password</label>
              <input type="text" name ="password" class="form-control" id="psw" placeholder="Enter password">
            </div>
              <button type="submit" class="btn btn-success btn-block"><span class="glyphicon glyphicon-off"></span> Login</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="submit" class="btn btn-danger btn-default pull-left" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span> Cancel</button>
        </div>
      </div>

    </div>
  </div>





<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">WebSiteName</a>
    </div>
    <ul class="nav navbar-nav">
      <li class="active"><a href="/">Home</a></li>
      {% if user_email %}
      <li><a href="{{url_for("show_history.main") }}">History</a></li>
      {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right">
    {% if not user_email %}

    <li id="login"><a href="#" onclick = "return false;"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <li><a href="{{url_for("verification_link_generation.main") }}"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
    {% else %}
    <li><a href="{{ url_for("logout.main") }}"><span class="glyphicon glyphicon-log-out"></span> Logout</a></li>
    {% endif %}
    </ul>
</div>

</nav>
<div class="row">
<div class="col-sm-2" id = "left-panel">
</div>
<div class="col-sm-8">
    {{ message }}
</div>
<div class="col-sm-2" id = "right-panel">
</div>
</div>
<script>
$(document).ready(function(){
$("#login").click(function(){
     $("#myModal").modal();
});
});
</script>
</body>